#bài 1:
list_of_colors = list(("blue", "teal","green"))
print("color list:") 
for item in list_of_colors: 
    print(item, end=', ')
print("")
a=int(input("input position: "))
print("item in position",a,":", list_of_colors[a-1])
#bài 2:
b=int(input("item to delete: "))
list_of_colors.pop(a-1)
print("new color list:", end=' ')
for item in list_of_colors:
    print(item, end=', ')
print("")
list_of_colors.remove(input("item to delete: "))
for item in list_of_colors:
    print(item, end=', ')
#bài 3
from turtle import *
color("red")
forward(40)
penup()
forward(20)
pendown()
color("orange")
forward(40)
penup()
forward(20)
pendown()
color("yellow")
forward(40)
penup()
forward(20)
pendown()
color("green")
forward(40)
penup()
forward(20)
pendown()
color("blue")
forward(40)
penup()
forward(20)
pendown()
color("violet")
forward(40)
penup()
forward(20)
pendown()
color("black")
shape("turtle")
mainloop()