name = input("Input your name: ")
email = input("Input your email: ")
password = input("Input your password: ")
print("Your name is: ", name)
print("Your email is: ", email)
print("Your password is: ", password)